version: '3.6'

services:
  client:
    image: react-app
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    container_name: client
    stdin_open: true
    command: npm start
    volumes:
      - /jestersvault/node_modules
      - ./client:/jestersvault
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports: 
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    networks:
      - jestersvault
    depends_on:
      - server

  server:
    image: api-server
    env_file: ./.env
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    command: npm start
    volumes:
      - /jestersvault/node_modules
      - ./server:/jestersvault
    environment:
      - DB_HOST=database
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
      - JWT_SECRET=$JWT_SECRET
      - CHOKIDAR_USEPOLLING=true
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    networks:
      - jestersvault
    depends_on:
      - database

  database:
    image: mongo
    env_file: ./.env
    container_name: database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    networks:
      - jestersvault
    volumes:
      - mongo-data:/data/db
    logging:
      driver: 'none'

networks:
  jestersvault:
    driver: bridge
volumes:
  mongo-data:
    driver: local