version: '3.6'

services:
  client:
    image: react-app
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    stdin_open: true
    command: npm start
    volumes:
      - /jestersvault/node_modules
      - ./client:/jestersvault
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports: 
      - "3000:3000"
    networks:
      - jestersvault
    depends_on:
      - server

  server:
    image: api-server
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    command: npm start
    volumes:
      - /jestersvault/node_modules
      - ./server:/jestersvault
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "8000:8000"
    networks:
      - jestersvault
    depends_on:
      - database

  database:
    image: mongo
    container_name: database
    ports:
      - "27017:27017"
    networks:
      - jestersvault
    volumes:
      - mongo-data:/data/db
    logging:
      driver: 'none'

networks:
  jestersvault:
    driver: bridge
volumes:
  mongo-data:
    driver: local